baseURL = "https://vladan.dev/"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = false
locale = "en-us"
disableKinds = ["taxonomy", "term"]
title = "Vladan Petrovic | Senior Software Engineer"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
