baseURL = "https://vladan.dev/"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = false
languageCode = "en-us"
rssLimit = 20
title = "Vladan Petrovic | Senior Software Engineer"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
