author = "Vladan Petrovic"
description = "The official portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
keywords = [
  "Vladan Petrovic",
  "Senior Software Engineer",
  "JavaScript",
  "React",
  "Angular",
  "Web Development",
  "Portfolio",
  "Software Engineer",
  "Senior Frontend Developer",
  "Web Developer",
  "Senior Fullstack Developer",
  "Senior Fullstack Engineer",
]

# Open Graph (OG) Meta Tags for social media sharing
locale = "en_US"
ogDescription = "Explore the portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
ogTitle = "Vladan Petrovic - Senior Software Engineer"

jobTitle = "Senior Software Engineer"
name = "Vladan Petrović"

# Section Titles
connectTitle = "Connect with me"
skillsTitle = "My Skills"

# Skills
[[skills]]
image = "javascript-logo"
name = "JavaScript"
url = "https://developer.mozilla.org/en-US/docs/Web/JavaScript"

[[skills]]
image = "typescript-logo"
name = "TypeScript"
url = "https://www.typescriptlang.org/"

[[skills]]
image = "react-logo"
name = "React"
url = "https://reactjs.org/"

[[skills]]
image = "angular-logo"
name = "Angular"
url = "https://angular.io/"

# Social Links
[[socialLinks]]
image = "linkedin-logo"
name = "LinkedIn"
url = "https://www.linkedin.com/in/vladanpet"

[[socialLinks]]
image = "github-logo"
name = "GitHub"
url = "https://github.com/vladanp"
