author = "Vladan Petrovic"
description = "The official portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
keywords = [
  "Vladan Petrovic",
  "Senior Software Engineer",
  "JavaScript",
  "React",
  "Angular",
  "Web Development",
  "Portfolio",
  "Software Engineer",
  "Senior Frontend Developer",
  "Web Developer",
  "Senior Fullstack Developer",
  "Senior Fullstack Engineer",
]

# Open Graph (OG) Meta Tags for social media sharing
locale = "en_US"
ogDescription = "Explore the portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
ogTitle = "Vladan Petrovic - Senior Software Engineer"

jobTitle = "Senior Software Engineer"
name = "Vladan Petrović"

# Section Titles
connectTitle = "Connect with me"
skillsTitle = "My Skills"

# Skills
[[skills]]
image200 = "images/javascript-logo-200.png"
image400 = "images/javascript-logo-400.png"
image800 = "images/javascript-logo-800.png"
name = "JavaScript"
url = "https://developer.mozilla.org/en-US/docs/Web/JavaScript"

[[skills]]
image200 = "images/typescript-logo-200.png"
image400 = "images/typescript-logo-400.png"
image800 = "images/typescript-logo-800.png"
name = "TypeScript"
url = "https://www.typescriptlang.org/"

[[skills]]
image200 = "images/react-logo-200.png"
image400 = "images/react-logo-400.png"
image800 = "images/react-logo-800.png"
name = "React"
url = "https://reactjs.org/"

[[skills]]
image200 = "images/angular-logo-200.png"
image400 = "images/angular-logo-400.png"
image800 = "images/angular-logo-800.png"
name = "Angular"
url = "https://angular.io/"

# Social Links
[[socialLinks]]
image200 = "images/linkedin-logo-200.png"
image400 = "images/linkedin-logo-400.png"
image800 = "images/linkedin-logo-800.png"
name = "LinkedIn"
url = "https://www.linkedin.com/in/vladanpet"

[[socialLinks]]
image200 = "images/github-logo-200.png"
image400 = "images/github-logo-400.png"
image800 = "images/github-logo-800.png"
name = "GitHub"
url = "https://github.com/vladanp"
