pre-commit:
  commands:
    format-check:
      glob: "*.{ts,js,mjs,css,json,yml,yaml,md,toml}"
      run: pnpm format:check
    lint:
      glob: "*.{ts,js,mjs}"
      run: pnpm lint

commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit {1}
