services:
  hugo:
    image: hugomods/hugo:debian-std-0.165.0
    ports:
      - "127.0.0.1:1313:1313"
    volumes:
      - ./assets:/src/assets:ro
      - ./config:/src/config:ro
      - ./content:/src/content:ro
      - ./layouts:/src/layouts:ro
      - ./static:/src/static:ro
    command: server --bind 0.0.0.0 --baseURL http://127.0.0.1:1313/ --disableFastRender --noHTTPCache
