baseURL = "https://vladan.dev/"
languageCode = "en-us"
title = "Vladan Petrovic | Senior Software Engineer"
author = "Vladan Petrovic"

[params]
  description = "The official portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
  author = "Vladan Petrovic"
  keywords = ["Vladan Petrovic", "Senior Software Engineer", "JavaScript", "React", "Angular", "Web Development", "Portfolio", "Software Engineer", "Frontend Developer", "Senior Frontend Developer", "Web Developer"]

  # Open Graph (OG) Meta Tags for social media sharing
  ogImage = "images/og-image.webp"
  ogTitle = "Vladan Petrovic - Senior Software Engineer"
  ogDescription = "Explore the portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
  locale = "en_US"

  # Twitter Meta Tags
  twitterCard = "summary_large_image"
  twitterSite = "@VladanPetrovic"
  twitterTitle = "Vladan Petrovic | Senior Software Engineer"
  twitterDescription = "The official portfolio of Vladan Petrovic, showcasing expertise in JavaScript, React, Angular and web development."
  twitterImage = "images/og-image.webp"

  name = "Vladan Petrovic"
  jobTitle = "Senior Software Engineer"

  # Section Titles
  connectTitle = "Connect with me"
  skillsTitle = "My Skills"

  # Social Links with updated image paths
  [[params.socialLinks]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/vladanpet"
    image = "linkedin-logo.png"

  [[params.socialLinks]]
    name = "GitHub"
    url = "https://github.com/vladanp"
    image = "github-logo.png"

  # Skills
  [[params.skills]]
    name = "JavaScript"
    image = "images/javascript-logo.png"
    url = "https://developer.mozilla.org/en-US/docs/Web/JavaScript"

  [[params.skills]]
    name = "TypeScript"
    image = "images/typescript-logo.png"
    url = "https://www.typescriptlang.org/"

  [[params.skills]]
    name = "React"
    image = "images/react-logo.png"
    url = "https://reactjs.org/"

  [[params.skills]]
    name = "Angular"
    image = "images/angular-logo.png"
    url = "https://angular.io/"

[taxonomies]
  tag = ""
  category = ""

[sitemap]
  filename = "sitemap.xml"
  priority = 1
  changefreq = "monthly"
  disable = false
