baseURL = "https://vladanp.github.io/"
languageCode = "en-us"
title = "Vladan Petrovic"
metaDescription = "Portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, and web development."
author = "Vladan Petrovic"
keywords = ["Vladan Petrovic", "Senior Software Engineer", "JavaScript", "React", "Web Development", "Portfolio"]

[params]
  name = "Vladan Petrovic"
  jobTitle = "Senior Software Engineer"

  # Open Graph (OG) Meta Tags for social media sharing
  ogImage = "images/og-image.png" # Replace with your actual image path
  ogDescription = "Portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, and web development."

  # Twitter Card Meta Tags
  twitterImage = "images/twitter-image.png" # Replace with your actual image path
  twitterCreator = "@yourTwitterHandle" # Replace with your actual Twitter handle
  twitterDescription = "Portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, and web development."

  [[params.socialLinks]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/vladanpet"

  [[params.socialLinks]]
    name = "GitHub"
    url = "https://github.com/vladanp"

  [[params.skills]]
    name = "JavaScript"
    image = "images/javascript-logo.webp"

  [[params.skills]]
    name = "React"
    image = "images/react-logo.webp"

[taxonomies]
  category = "categories"
  tag = "tags"

  # Example of adding a custom taxonomy
  skill = "skills"