baseURL = "https://vladan.dev/"
title = "Vladan Petrovic | Senior Software Engineer"

[params]
  description = "The official portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
  author = "Vladan Petrovic"
  keywords = ["Vladan Petrovic", "Senior Software Engineer", "JavaScript", "React", "Angular", "Web Development", "Portfolio", "Software Engineer", "Frontend Developer", "Senior Frontend Developer", "Web Developer"]

  # Open Graph (OG) Meta Tags for social media sharing
  ogImage = "images/og-image.webp"
  ogTitle = "Vladan Petrovic - Senior Software Engineer"
  ogDescription = "Explore the portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, Angular, and modern web development."
  locale = "en_US"

  name = "Vladan Petrović"
  jobTitle = "Senior Software Engineer"

  # Section Titles
  connectTitle = "Connect with me"
  skillsTitle = "My Skills"

  # Social Links
  [[params.socialLinks]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/vladanpet"
    image = "linkedin-logo"

  [[params.socialLinks]]
    name = "GitHub"
    url = "https://github.com/vladanp"
    image = "github-logo"

  # Skills
  [[params.skills]]
    name = "JavaScript"
    image = "javascript-logo"
    url = "https://developer.mozilla.org/en-US/docs/Web/JavaScript"

  [[params.skills]]
    name = "TypeScript"
    image = "typescript-logo"
    url = "https://www.typescriptlang.org/"

  [[params.skills]]
    name = "React"
    image = "react-logo"
    url = "https://reactjs.org/"

  [[params.skills]]
    name = "Angular"
    image = "angular-logo"
    url = "https://angular.io/"

[taxonomies]
  tag = ""
  category = ""

[sitemap]
  filename = "sitemap.xml"
  priority = 1.0
  changefreq = "yearly"
  disable = false

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDocumentTags = true
