baseURL = "https://www.vladan.dev/"
languageCode = "en-us"
title = "Vladan Petrovic"

[params]
  description = "Portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, and web development."
  author = "Vladan Petrovic"
  keywords = ["Vladan Petrovic", "Senior Software Engineer", "JavaScript", "React", "Web Development", "Portfolio"]

  # Open Graph (OG) Meta Tags for social media sharing
  ogImage = "images/og-image.webp"
  ogDescription = "Portfolio of Vladan Petrovic, a Senior Software Engineer specializing in JavaScript, React, and web development."

  name = "Vladan Petrović"
  jobTitle = "Senior Software Engineer"

  # Section Titles
  connectTitle = "Connect with me"
  skillsTitle = "My Skills"

  # Social Links with updated image paths
  [[params.socialLinks]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/vladanpet"
    image = "linkedin-logo.png"

  [[params.socialLinks]]
    name = "GitHub"
    url = "https://github.com/vladanp"
    image = "github-logo.png"

  # Skills
  [[params.skills]]
    name = "JavaScript"
    image = "images/javascript-logo.png"
    url = "https://developer.mozilla.org/en-US/docs/Web/JavaScript"

  [[params.skills]]
    name = "TypeScript"
    image = "images/typescript-logo.png"
    url = "https://www.typescriptlang.org/"

  [[params.skills]]
    name = "React"
    image = "images/react-logo.png"
    url = "https://reactjs.org/"

  [[params.skills]]
    name = "Angular"
    image = "images/angular-logo.png"
    url = "https://angular.io/"

[taxonomies]
  tag = ""
  category = ""

[sitemap]
  filename = "sitemap.xml"
  priority = 0.5
  changefreq = "monthly"
  disable = false
