name: SEO Audit

on:
  workflow_run:
    workflows: ["Deploy Hugo Site"]
    types:
      - completed

jobs:
  seo_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          uploadArtifacts: true
          configPath: "./lighthouserc.json"
