name: SEO Audit

on:
  workflow_run:
    workflows: ["Deploy Hugo Site and Create Release"]
    types:
      - completed

jobs:
  seo_audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Audit using Lighthouse
        uses: googlechrome/lighthouse-ci@v0.15.1
        with:
          urls: "https://vladan.dev"
          configPath: "./lighthouserc.json"
