name: Deploy Hugo Site and Create Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.133.1"

      - name: Build the site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          allow_empty_commit: true

  versioning:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0" # Fetch all history for accurate versioning

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1.48.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          WITH_V: true
          RELEASE_BRANCHES: main

  release:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release Notes
        id: release_notes
        run: |
          # Collect commit messages from the last tag to HEAD
          tag=$(git describe --tags --abbrev=0)
          release_notes=$(git log $tag..HEAD --pretty=format:"%h %s")
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "${release_notes}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
