name: Deploy Hugo Site

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # Trigger on version tags for releases

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Adding permissions for versioning within the deploy job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0" # Full history required for versioning

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.133.1"

      - name: Build the site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          allow_empty_commit: true

  release:
    runs-on: ubuntu-latest
    needs: deploy
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Generate Release Notes
        run: |
          echo "# Release Notes" > release-notes.txt
          git log --oneline ${GITHUB_REF#refs/tags/}..HEAD >> release-notes.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
